version: '3.8'

services:
  oltp_sqlserver:
    build: .
    container_name: db_oltp_fluxo
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AnaliseDados@2026!
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 25 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'AnaliseDados@2026!' -C -Q \"RESTORE DATABASE AdventureWorks FROM DISK = '/var/opt/mssql/backup/AdventureWorks2025.bak' WITH REPLACE, MOVE 'AdventureWorks' TO '/var/opt/mssql/data/AdventureWorks.mdf', MOVE 'AdventureWorks_log' TO '/var/opt/mssql/data/AdventureWorks_log.ldf'\" &&
      wait
      "

  olap_postgres:
    image: postgres:16-alpine
    container_name: db_olap_dw
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dw_admin
      - POSTGRES_PASSWORD=DataWarehouse@2026!
      - POSTGRES_DB=dw_analise_fluxo
    volumes:
      - postgres_dw_data:/var/lib/postgresql/data

volumes:
  postgres_dw_data:
